//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHab.Wpf.View.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenHab.Wpf.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenHAB Wpf Rule Designer ähnelt.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness ähnelt.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Application ähnelt.
        /// </summary>
        public static string CloseApplication {
            get {
                return ResourceManager.GetString("CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect automatically ähnelt.
        /// </summary>
        public static string ConnectAutomatically {
            get {
                return ResourceManager.GetString("ConnectAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given IP adress will be stored and connection is established automatically when possible, ähnelt.
        /// </summary>
        public static string ConnectAutomaticallyExplanation {
            get {
                return ResourceManager.GetString("ConnectAutomaticallyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection to the server has been established successfully. ähnelt.
        /// </summary>
        public static string ConnectionEstablished {
            get {
                return ResourceManager.GetString("ConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check if the connection can be established. ähnelt.
        /// </summary>
        public static string ConnectionIndicator {
            get {
                return ResourceManager.GetString("ConnectionIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server is online ähnelt.
        /// </summary>
        public static string ConnectionOnline {
            get {
                return ResourceManager.GetString("ConnectionOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect to another server. ähnelt.
        /// </summary>
        public static string ConnectToAnotherServer {
            get {
                return ResourceManager.GetString("ConnectToAnotherServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect to server ähnelt.
        /// </summary>
        public static string ConnectToServer {
            get {
                return ResourceManager.GetString("ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new rule ähnelt.
        /// </summary>
        public static string CreateRule {
            get {
                return ResourceManager.GetString("CreateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes this rule ähnelt.
        /// </summary>
        public static string DeleteRule {
            get {
                return ResourceManager.GetString("DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag item over the actions section to add it as an action ähnelt.
        /// </summary>
        public static string DragItemToAddAsAction {
            get {
                return ResourceManager.GetString("DragItemToAddAsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field must not be empty. Please enter a numeric value ähnelt.
        /// </summary>
        public static string FieldMustNotBeEmpty {
            get {
                return ResourceManager.GetString("FieldMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal characters, please enter numeric values only ähnelt.
        /// </summary>
        public static string IllegalCharacters {
            get {
                return ResourceManager.GetString("IllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP address: ähnelt.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items ähnelt.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not connect to the server with given ip address. ähnelt.
        /// </summary>
        public static string NoConnectionEstablished {
            get {
                return ResourceManager.GetString("NoConnectionEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please type in a valid IP address. (e.g.: 192.168.1.1) ähnelt.
        /// </summary>
        public static string NotAValidIpAddress {
            get {
                return ResourceManager.GetString("NotAValidIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {}Connection has been terminated. Trying to reconnect... ({0}) ähnelt.
        /// </summary>
        public static string ReconnectionAttemptFormat {
            get {
                return ResourceManager.GetString("ReconnectionAttemptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right click here for more options &lt;NOT IMPLEMENTED&gt; ähnelt.
        /// </summary>
        public static string RightClickItemForMoreOptions {
            get {
                return ResourceManager.GetString("RightClickItemForMoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rules ähnelt.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This rule is currently enabled. Click to disable it. ähnelt.
        /// </summary>
        public static string RuleToggleOff {
            get {
                return ResourceManager.GetString("RuleToggleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This rule is currently disabled. Click to enable it. ähnelt.
        /// </summary>
        public static string RuleToggleOn {
            get {
                return ResourceManager.GetString("RuleToggleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Performs all actions of this rule immediately ähnelt.
        /// </summary>
        public static string RunRule {
            get {
                return ResourceManager.GetString("RunRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saturation ähnelt.
        /// </summary>
        public static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please type in the address of the OpenHab server component you would like to connect to. ähnelt.
        /// </summary>
        public static string ServerAddressPrompt {
            get {
                return ResourceManager.GetString("ServerAddressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sitemaps ähnelt.
        /// </summary>
        public static string Sitemaps {
            get {
                return ResourceManager.GetString("Sitemaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start typing to filter everything... ähnelt.
        /// </summary>
        public static string StartTypeToBrowseForEverything {
            get {
                return ResourceManager.GetString("StartTypeToBrowseForEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start typing to filter things... ähnelt.
        /// </summary>
        public static string StartTypeToBrowseForThings {
            get {
                return ResourceManager.GetString("StartTypeToBrowseForThings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Things ähnelt.
        /// </summary>
        public static string Things {
            get {
                return ResourceManager.GetString("Things", resourceCulture);
            }
        }
    }
}
